services:
  app:
    image: node:20-alpine
    command: sh -c "npm install && npm run build"
    container_name: credits
    working_dir: /app
    build: .
    volumes:
      - ./:/app

networks:
  default:
    external: true
    name: scoobydoo